//! Byte-neutral responsibility split of the former monolith; see the parent module.

use super::*;
use crate::native::cfg::loopforest::post_idom;

/// Synthesized pass-through merge-block name prefix (kept distinct from any AIR label).
pub(in crate::native) const SPLIT_PREFIX: &str = "%metal2vulkan.lmerge.";

// Same-memory structurizer synthesized-name tokens. These never cross the emit->SPIR-V reparse seam,
// so they are a purely internal naming protocol; centralizing every set/match through these constants
// is what keeps a generator and its later matcher from drifting (the class Phase 1c closed for the
// switch prefixes).

/// Distinguishes the terminal-exit private-return clone inside the `SPLIT_PREFIX` family
/// (`%metal2vulkan.lmerge.texitret*`). Shared by the generator (`synth_terminal_return_clone`) and
/// the convergence matcher (`terminal_exit_convergence`) so the set/match pair cannot drift.
pub(in crate::native) const TEXITRET_TOKEN: &str = "texitret";
/// Distinguishes the terminal-loop private-return clone inside the `SPLIT_PREFIX` family
/// (`%metal2vulkan.lmerge.tloopret*`), generated by `privatize_single_loop_return_exit`.
pub(in crate::native) const TLOOPRET_TOKEN: &str = "tloopret";
/// Distinguishes the unique per-construct selection merge inside the `SPLIT_PREFIX` family
/// (`%metal2vulkan.lmerge.sel*`).
pub(in crate::native) const SEL_TOKEN: &str = "sel";

/// Synthesized do-while rotated-continue block prefix (`%metal2vulkan.cont.*`).
pub(in crate::native) const CONT_PREFIX: &str = "%metal2vulkan.cont.";
/// Synthesized multi-exit critical-edge dispatch-block prefix (`%metal2vulkan.exitedge.*`).
pub(in crate::native) const EXIT_EDGE_PREFIX: &str = "%metal2vulkan.exitedge.";
/// Synthesized multi-exit selector value prefix (`%metal2vulkan.exitsel.*`).
pub(in crate::native) const EXIT_SEL_PREFIX: &str = "%metal2vulkan.exitsel.";

/// True when `name` is a synthesized terminal-exit private-return merge block
/// (`%metal2vulkan.lmerge.texitret*`). No production DECISION calls this any more (the convergence
/// matcher and the single-exit-return synthesizer read the typed [`BlockRole::TerminalExitReturn`]
/// tag instead of the name); it survives only as the tag-assignment seam [`role_for_name`] uses to
/// stamp a block whose name is the carried identity across a clone/rename.
pub(in crate::native) fn is_terminal_exit_return_name(name: &str) -> bool {
    name.strip_prefix(SPLIT_PREFIX)
        .is_some_and(|rest| rest.starts_with(TEXITRET_TOKEN))
}

/// The [`BlockRole`] a block carries given the NAME it is (re)built with. Used at the clone/rename
/// seam — where a block's name is the identity carried from its source (a cloned `texitret` block
/// keeps a `texitret`-prefixed name, a renamed-away one does not) — so the stamped role exactly
/// tracks the name. Pure synthesizers of a fresh name stamp their role directly (`Normal`, or
/// `TerminalExitReturn` at the one terminal-return clone site) rather than routing through here.
/// Byte-neutral by construction: `role == is_terminal_exit_return_name(name)` at every construction
/// site, so a consumer reading the tag decides exactly as the retired name match did.
pub(in crate::native) fn role_for_name(name: &str) -> BlockRole {
    if is_terminal_exit_return_name(name) {
        BlockRole::TerminalExitReturn
    } else if name.starts_with(SPLIT_PREFIX) {
        BlockRole::LMerge
    } else if name.starts_with(super::super::blocks::SWITCH_BYPASS_PREFIX) {
        BlockRole::SwitchBypass
    } else {
        BlockRole::Normal
    }
}

/// Full structured plan for a function: forest-augmented, structured-ordered blocks plus the
/// loop/branch/switch merge maps consumed by emission. Instruction-local emission preserves this
/// source CFG's edge identities through its real emitted block exits.
pub(in crate::native) struct StructuredPlan {
    pub(in crate::native) blocks: Vec<BodyBlock>,
    pub(in crate::native) loop_merges: HashMap<String, LoopMergeInfo>,
    pub(in crate::native) branch_merges: HashMap<(String, String), String>,
    pub(in crate::native) branch_merges_by_header: HashMap<String, String>,
    pub(in crate::native) switch_merges: HashMap<String, String>,
}

/// Build the structured plan for a function, or `None` if the current modules cannot FULLY structure
/// it (a loop needs node-splitting we do not do; or a conditional/switch has no synthesizable unique
/// merge — exit-reconvergence, or a phi-carrying shared merge). Combines `forest_loop_merges` (module:
/// loop merges + merge==continue split), `unique_selection_merges` (module 2: per-construct selection
/// merges), and `structured_order` (module 1: dominator-tree, merge-last ordering). When `Some`, every
/// loop and every conditional/switch header has a unique merge, so the emitter emits a complete
/// structured CFG without a retained-module control-flow rewrite.
/// Block-count ceiling for the cross-arm-EDGE machinery (self-check 3 + the 9th-attempt clone). A pure
/// PERFORMANCE bound for cross-arm cloning and its repeated planner invocations. The final
/// cross-arm correctness check itself is never size-gated: a large function must reject an invalid
/// plan just as reliably as a small one. Every landed clone win is a small function (<=126 emitted
/// blocks), so only the mutation/replanning machinery is kept to modest candidates.
pub(in crate::native) const CROSS_ARM_EDGE_MAX_BLOCKS: usize = 300;

/// Reject-only loop-exit selection planning is intentionally bounded to modest CFGs. It walks a
/// candidate's complete in-loop region to prove that every path either reaches the candidate or exits
/// through an enclosing loop role; the bound keeps that proof from becoming a quadratic retry cost on
/// giant descriptor-index functions. A skipped graph follows the existing relooper retry path.
pub(in crate::native) const LOOP_EXIT_SELECTION_MAX_BLOCKS: usize = 300;

/// Merge-preserving region-cross-arm planning is also bounded to modest CFGs in the default ladder.
/// The clone driver has per-region and total-growth caps, but a grown candidate is fed back through
/// several planner variants. Large residual CFGs can spend minutes cloning and re-planning before
/// rejecting, so the ladder bounds both the input and cloned output; skipped candidates remain on the
/// established fallback path. The lower-level clone remains available to single-shot callers with
/// their own proof/budget.
pub(in crate::native) const REGION_CROSS_ARM_LADDER_MAX_BLOCKS: usize = 300;

/// The pre-ladder shared-continuation privatization is a safety repair for malformed nested
/// selection/switch continuations that can otherwise look admissible to the source-CFG planner. Keep
/// that repair on modest CFGs: on broad descriptor/indexing bodies the combined switch/deep clone can
/// inflate a small function into several hundred synthetic merge blocks, then feed that large graph
/// through every later ladder rung before the planner returns to the original CFG.
pub(in crate::native) const SHARED_CONTINUATION_LADDER_MAX_BLOCKS: usize = 300;

/// Selection-merge synthesis can turn compact straight-line decision trees into hundreds of
/// `%metal2vulkan.lmerge.sel*` pass-through blocks. Keep a fixed allowance for modest CFGs and a
/// one-block-per-source-block allowance for generated CFGs: a large function can legitimately need
/// more than 300 private selection merges, while superlinear growth still indicates runaway construction.
pub(in crate::native) const SELECTION_SYNTH_GROWTH_MAX_BLOCKS: usize = 300;

/// Hard ceiling for the source-CFG structured planner. A rejection selects raw-CFG construction;
/// on massive functions, proving that the local planner cannot help can cost minutes before reaching
/// that representation. This bound remains far above the local construction caps.
pub(in crate::native) const STRUCTURED_PLAN_MAX_BLOCKS: usize = 3000;

/// Bound repeated local-planner work by graph shape, not only by block count. The attempt ladder
/// recomputes ownership for each branching header; dense generated CFGs below the block ceiling can
/// otherwise exceed the end-to-end translation budget before reaching the linear whole-CFG owner.
const LOCAL_STRUCTURED_PLAN_WORK_BUDGET: usize = 4096;
const LOCAL_STRUCTURED_PLAN_MAX_BLOCKS: usize = 128;

pub(in crate::native) fn exceeds_local_structured_plan_budget(blocks: &[BodyBlock]) -> bool {
    if blocks.len() > LOCAL_STRUCTURED_PLAN_MAX_BLOCKS {
        return true;
    }
    let branching = blocks
        .iter()
        .filter(|block| block_successors(block).len() > 1)
        .count();
    blocks.len().saturating_mul(branching.max(1)) > LOCAL_STRUCTURED_PLAN_WORK_BUDGET
}

/// Whether a structural retry actually changed its source CFG. `BodyBlock` deliberately does not need
/// a public `PartialEq`; the planner only needs this local name/carrier comparison to distinguish a
/// forced lowering that preserves block count (for example an empty switch) from a true no-op. The
/// comparison is carrier-first (structural `TirBlock` Debug — the carrier has no derived `Eq` because
/// its `RetEmit` carries floats), with a line fallback for the pre-`populate` window. Byte-identical to
/// the line comparison: the only blocks that differ here are lowered switch blocks, whose lines AND
/// carrier both change together (a non-switch or unchanged block is pushed as an exact clone).
pub(in crate::native) fn blocks_changed(before: &[BodyBlock], after: &[BodyBlock]) -> bool {
    before.len() != after.len()
        || before
            .iter()
            .zip(after)
            .any(|(left, right)| left.name != right.name || block_body_changed(left, right))
}

/// Whether a natural loop is entered from both inside and outside a still-open nested selection.
/// Such a selection cannot reconverge before the loop: one arm enters the shared loop while another
/// path that the selection does not own enters the same header. The loop region therefore needs
/// whole-CFG ownership construction before merge assignment; assigning a private selection merge on
/// the unowned shared loop produces a live path that bypasses that merge.
pub(in crate::native) fn requires_shared_loop_entry_ownership(blocks: &[BodyBlock]) -> bool {
    let forest = analyze(blocks);
    let post_idoms = post_idom(blocks);
    let mut predecessors = HashMap::<String, Vec<&str>>::new();
    for block in blocks {
        for successor in block_successors(block) {
            predecessors
                .entry(successor)
                .or_default()
                .push(block.name.as_str());
        }
    }
    for loop_info in &forest.loops {
        let loop_body = loop_info
            .body
            .iter()
            .map(String::as_str)
            .collect::<HashSet<_>>();
        let forward_predecessors = predecessors
            .get(loop_info.header.as_str())
            .into_iter()
            .flatten()
            .copied()
            .filter(|predecessor| !loop_body.contains(predecessor))
            .collect::<Vec<_>>();
        if forward_predecessors.len() < 2 {
            continue;
        }
        for header in blocks {
            if conditional_branch_targets(header).is_none() {
                continue;
            }
            let Some(natural_merge) = post_idoms.get(&header.name) else {
                continue;
            };
            let owned = forward_predecessors
                .iter()
                .filter(|predecessor| forest.dominates(&header.name, predecessor))
                .copied()
                .collect::<Vec<_>>();
            if owned.is_empty() || owned.len() == forward_predecessors.len() {
                continue;
            }
            if owned
                .iter()
                .any(|predecessor| !forest.dominates(natural_merge, predecessor))
            {
                return true;
            }
        }
    }
    false
}

fn block_body_changed(left: &BodyBlock, right: &BodyBlock) -> bool {
    match (&left.typed, &right.typed) {
        (Some(l), Some(r)) => format!("{l:?}") != format!("{r:?}"),
        // Both un-lowered (no terminator) — an unchanged clone; a mixed None/Some is a real change.
        (None, None) => false,
        _ => true,
    }
}

pub(in crate::native) fn structured_plan(blocks: &[BodyBlock]) -> Option<StructuredPlan> {
    if blocks.len() > STRUCTURED_PLAN_MAX_BLOCKS {
        return None;
    }
    // A nested conditional or switch case can enter a continuation also reached by a sibling/enclosing
    // arm before either reaches its shared natural merge. The normal unique-merge synth can only
    // redirect direct predecessors of that merge, so the nested construct would otherwise escape through
    // the shared continuation. Privatize the continuation first; this is intentionally before the base
    // admission attempt because that malformed graph can look structurally admissible to the source-CFG
    // planner while still failing spirv-val. A no-op leaves every other graph byte-identical.
    let deep_shared = privatize_shared_continuations_for_ladder(blocks);
    if deep_shared.len() != blocks.len() {
        if let Some(plan) = structured_plan_ladder(&deep_shared, false) {
            return finalize_loop_role_switches(plan);
        }
        if let Some(plan) = structured_plan_ladder(&deep_shared, true) {
            return finalize_loop_role_switches(plan);
        }
    }
    // The helper returns an owned no-op clone when no ladder repair applies. Do not retain that
    // second full CFG through every later retry of a large function.
    drop(deep_shared);

    // Two full passes of the attempt ladder. The FIRST runs with `allow_bare_exit=false` — byte-identical
    // to the pre-lever behavior, so every currently-admitting function is untouched. Only if the whole
    // ladder rejects (the function currently returns None → the primary fallback emits) do we re-run it
    // with `allow_bare_exit=true` (Keystone 2): every attempt —
    // including the cross-arm/synth clones — then may SKIP a block whose conditional arms are a bare
    // structured break/continue (one arm is an enclosing loop's merge/continue) instead of rejecting
    // `branch-no-merge`, with `bare_exit_escape_reason` rejecting any plan the skip unmasks a residual
    // unstructured exit in. Re-running the ENTIRE ladder (not a raw-blocks sweep) is required because a
    // merge-inloop function often needs a cross-arm/synth CLONE first, then the bare-exit skip on the
    // residual latch. The second pass is byte-neutral for admitting functions (never reached) and its only
    // new admissions are functions that today fall through to the fallback.
    if blocks.len() > TERMINAL_EXIT_SELECTION_MAX_BLOCKS {
        // Large generated CFGs go directly to the whole-CFG construct-tree planner in the emitter.
        // Even one speculative source-CFG candidate can coexist with the fallback's ownership graph
        // long enough to exceed the per-translation live-memory budget. The global path is the only
        // planner capable of resolving compound straddle/cross-arm ownership anyway, so a preliminary
        // local candidate adds cost without broadening support.
        return None;
    } else {
        if let Some(plan) = structured_plan_ladder(blocks, false) {
            return finalize_loop_role_switches(plan);
        }
        if let Some(plan) = structured_plan_ladder(blocks, true) {
            return finalize_loop_role_switches(plan);
        }
    }
    // Reject-only shared-merge separation: when divergent return-like exits are the structural reason
    // a conditional has no natural merge, route them through one synthesized function exit and rerun
    // the unchanged ladder. A candidate is retained only when that shared exit makes the rejected CFG
    // structurable; a function that merely contains multiple returns but still rejects is untouched.
    // An already-admitted function never reaches this construction.
    if let Some(plan) = structured_plan_divergent_exit(blocks) {
        return finalize_loop_role_switches(plan);
    }
    None
}

/// A source-valid switch may branch directly to an enclosing loop's continue/merge role while
/// another arm remains in the loop. Source dominance can admit that graph, but SPIR-V case
/// constructs cannot borrow an enclosing loop-role block. Inspect the completed ownership map
/// cheaply and pay for loop analysis/lowering only when a switch actually targets one of its roles.
fn finalize_loop_role_switches(plan: StructuredPlan) -> Option<StructuredPlan> {
    if plan.blocks.len() > LOOP_EXIT_SELECTION_MAX_BLOCKS {
        return Some(plan);
    }
    let loop_roles = plan
        .loop_merges
        .values()
        .flat_map(|info| [&info.merge, &info.continue_target])
        .collect::<HashSet<_>>();
    let targets_loop_role = plan.blocks.iter().any(|block| {
        block.typed.as_ref().is_some_and(|typed| {
            matches!(
                typed.terminator,
                crate::native::tir::TirTerminator::Switch { .. }
            ) && block_successors(block)
                .iter()
                .any(|target| loop_roles.contains(target))
        })
    });
    if !targets_loop_role {
        return Some(plan);
    }
    let lowered_switches = super::blocks::lower_loop_exit_switches(&plan.blocks);
    if !blocks_changed(&plan.blocks, &lowered_switches) {
        return Some(plan);
    }
    structured_plan(&lowered_switches)
}

/// Final reject-only construction for divergent function exits. Return unification creates the common
/// post-dominator. If that phi-carrying exit is still shared with enclosing paths, clone only its
/// immediate shared predecessors for the nested entries; the ordinary ladder can then synthesize each
/// selection's private merge. This is the shared-merge separation C1 needs; already-admitted functions
/// never reach it.
pub(in crate::native) fn structured_plan_divergent_exit(
    blocks: &[BodyBlock],
) -> Option<StructuredPlan> {
    let single_exit = super::clone_crossarm::separate_divergent_selection_exits(blocks)?;
    let shared_exit = super::clone_crossarm::privatize_shared_phi_exit_predecessors(&single_exit);
    if !blocks_changed(&single_exit, &shared_exit) {
        return None;
    }
    for allow_bare_exit in [false, true] {
        if let Some(plan) = structured_plan_ladder(&shared_exit, allow_bare_exit) {
            return Some(plan);
        }
    }
    None
}

/// Try the terminal-return policy matrix while sharing its rewritten CFG and fixed-point merge map.
/// Keeping this as one ladder rung makes the relatively expensive preparation both explicit and
/// impossible to duplicate accidentally when retry ordering changes.
fn structured_plan_terminal_attempts(
    blocks: &[BodyBlock],
    allow_bare_exit: bool,
) -> Option<StructuredPlan> {
    // On large CFGs, the full terminal ownership matrix composes a source-linear return split with
    // six complete loop/selection replans. That is not a bounded-memory operation: deeply generated
    // control flow can add hundreds of terminal owners before every variant rejects for an unrelated
    // cross-arm defect. Leave those functions to the construct-tree/relooper retry, which owns the
    // whole CFG and can resolve both relationships in one pass. The exact linear terminal primitive
    // itself remains available to the dedicated planner entry point and its regression coverage.
    if blocks.len() > TERMINAL_EXIT_SELECTION_MAX_BLOCKS {
        return None;
    }
    let prepared_terminal = prepare_terminal_exit_selection(blocks);
    for loop_exit_selection in [true, false] {
        for (converge, break_aware) in [(false, false), (true, false), (true, true)] {
            if let Some(plan) = structured_plan_inner8(
                blocks,
                converge,
                break_aware,
                false,
                allow_bare_exit,
                loop_exit_selection,
                true,
                false,
                prepared_terminal.as_ref(),
            ) {
                return Some(plan);
            }
        }
    }
    None
}

pub(in crate::native) fn structured_plan_ladder(
    blocks: &[BodyBlock],
    allow_bare_exit: bool,
) -> Option<StructuredPlan> {
    // Isolating the S15 trivial-cross-arm pre-pass to functions the base path cannot structure: try the
    // blocks as-is first, so every CURRENTLY-admitting function is byte-identical; only if that rejects,
    // retry on the trivial-pass-through-privatized graph (`privatize_trivial_cross_arm` — clone a shared
    // single-`br` arm so its header dominates it). A rejecting function with no such shape privatizes to
    // an identical-length graph, so we skip the redundant retry. The plan self-checks run inside
    // `structured_plan_inner4`, so this cannot over-admit the gate. See [[metal2vulkan-native-emitter]]
    // "S15 trivial cross-arm privatization". Global measurement override (`METAL2VULKAN_CONVERGE_INLOOP`):
    // force in-loop collision convergence on ALL attempts (not just the reject-triggered one below), to
    // measure the large-scale byte churn the broad form would cause. Default false → base-admitting
    // functions stay byte-identical.
    let force_converge = crate::env_vars::converge_inloop();
    if let Some(plan) =
        structured_plan_inner4(blocks, force_converge, false, false, allow_bare_exit)
    {
        return Some(plan);
    }
    let privatized = super::clone_crossarm::privatize_trivial_cross_arm(blocks);
    if privatized.len() != blocks.len() {
        if let Some(plan) =
            structured_plan_inner4(&privatized, force_converge, false, false, allow_bare_exit)
        {
            return Some(plan);
        }
    }
    // Trivial privatization returns an owned no-op clone on the common decline path. Its only
    // consumer is the attempt above; retaining it beside `region` multiplies peak CFG memory.
    drop(privatized);
    // Third attempt: the merge-PRESERVING dominated-region clone for multi-successor / def-carrying
    // cross-arm shared arms (`privatize_region_cross_arm`). Unlike the trivial pass-through clone it
    // duplicates a whole dominated subtree up to its reconvergence boundary, so it rescues the dominant
    // `selection:cross-arm-shared` class. Applied AFTER the trivial pre-pass and computed on the
    // ORIGINAL blocks. This avoids chaining the broad region clone onto an already cloned graph,
    // where a dominance-only model cannot prove structured-exit completeness. Existing plan
    // self-checks still gate adoption, and the clone also remains available in the spirv-val-gated
    // `cfg_restructure` retry for residual cross-arm shapes.
    let region = privatize_region_cross_arm_for_ladder(blocks);
    if region.len() != blocks.len() {
        if let Some(plan) =
            structured_plan_inner4(&region, force_converge, false, false, allow_bare_exit)
        {
            return Some(plan);
        }
    }
    // Fourth attempt (M-B1): reject-triggered in-loop merge convergence. Only functions the base +
    // cross-arm attempts could NOT structure reach here, so this is byte-identical for every currently-
    // admitting function; it rescues the dominant `cond-phi-shared/loop-role/merge-inloop` class (07 and
    // the 107-fn bucket) by giving a loop a distinct merge when an IN-LOOP selection shares it. Floor-safe:
    // the resulting plan is admitted only after the planner's structural self-check.
    if let Some(plan) = structured_plan_inner4(blocks, true, false, false, allow_bare_exit) {
        return Some(plan);
    }
    // Loop-exit convergence: a selection inside a loop may have a real in-loop convergence point even
    // though ordinary post-dominance reports the loop merge: paths that do not reach that point break
    // or continue the enclosing loop. Treat those loop-role paths as structured exits and retain the
    // proven in-loop convergence as the selection merge. This is reject-only and independently checks
    // every arm region, so base-admitting functions remain byte-identical and malformed escapes still
    // fall back. It intentionally runs before the multi-level-switch guard: the proof covers switch
    // arms too, whereas the later break-aware post-dominator attempt only handles direct conditionals.
    if blocks.len() <= LOOP_EXIT_SELECTION_MAX_BLOCKS {
        let lowered_switches = super::blocks::lower_loop_exit_switches(blocks);
        if blocks_changed(blocks, &lowered_switches) {
            // A loop-breaking switch must use the ladder form. Do not fall back to the raw `OpSwitch`
            // plan if this lowered graph declines: that raw form can look source-structured while
            // spirv-val rejects its loop-exit case construct.
            if let Some(plan) =
                structured_plan_inner5(&lowered_switches, true, false, false, allow_bare_exit, true)
            {
                return Some(plan);
            }
        } else if let Some(plan) =
            structured_plan_inner5(blocks, true, false, false, allow_bare_exit, true)
        {
            return Some(plan);
        }
    } else if let Some(plan) =
        structured_plan_inner5(blocks, true, false, false, allow_bare_exit, true)
    {
        // The general convergence refinement remains internally capped, but the linear loop-entry
        // terminal proof is valid at any size. Large graphs skip only switch lowering and the
        // expensive candidate search, not this exact structural retry.
        return Some(plan);
    }
    // Guard: skip the 5th/6th attempts for functions containing a SWITCH. The merge-inloop fix targets
    // conditional (2-arm) guarded breaks; these attempts only ADMIT the function, and an admitted switch
    // whose case-construct dominance the source-CFG self-check cannot verify (source-CFG dominance ≠
    // emitted structural dominance — dead-end #6) can emit invalid SPIR-V that the retry path would
    // otherwise handle validly (`Switch header does not structurally dominate its case construct`,
    // banked `02/387ebaa9` family). Leave only genuine multi-level-break switches to the relooper retry:
    // the M1b default (`switch_gate_excludes`) excludes just an in-loop switch with a loop-exiting arm;
    // a loop-free switch (or an in-loop switch whose arms all stay in the loop) is safe to admit.
    if switch_gate_excludes(blocks) {
        // The switch guard excludes the straddle and cross-arm retry families below, but a shared
        // function return is an independent structural exit and remains safe to prove here.
        return structured_plan_terminal_attempts(blocks, allow_bare_exit);
    }
    // Fifth attempt (Keystone 2): converge PLUS break-aware selection merges. The 4th attempt gives an
    // in-loop-collided loop a distinct merge and rotates its do-while latch to `{merge, continue}`, but
    // then a later in-loop GUARDED-BREAK selection (`if(!c) break; body`) still claims that loop merge as
    // its post-dominator (the break arm pollutes it), so `synth_unique_selection_merge` redirects the
    // latch's break edge and the plan rejects `branch-no-merge` on the latch (the residual
    // `cond-phi-shared/loop-role/merge-inloop` reject). Break-aware selection merges
    // (`break_aware_selection_merges`) cut the guarded break's edge to the loop merge, so the selection
    // reconverges at its non-break arm and never claims the loop merge — the latch is never redirected,
    // fixing the reject at its SOURCE (unlike LOOP_BREAK_PROTECT, which kept the break edge into the
    // claimed loop merge and over-admitted into `branches to the selection construct` invalidity;
    // dead-end #19). Reached ONLY after all four prior attempts reject, so every currently-admitting
    // function stays byte-identical; the resulting plan is admitted only after its structural
    // self-check.
    if let Some(plan) = structured_plan_inner4(blocks, true, true, false, allow_bare_exit) {
        return Some(plan);
    }
    // Sixth attempt (Keystone 2): reject-triggered straddle-loop-merge restructure on the PRIMARY
    // path. `restructure_straddle_loop_merges` — the
    // proven M-B1/05 `cfg_restructure` retry pre-pass — gives a loop whose exit merge straddles an
    // enclosing construct its OWN pass-through merge, then the destraddled graph re-runs the inner
    // ladder (base → converge → converge+break-aware). Targets the `selection:straddle-loop-merge`
    // reject class (93 banked ok-INVALID rows, the largest CFG-reject bucket of the M-B2
    // `--primary-val-check` floor). Reached ONLY after every prior attempt rejects, so currently-
    // admitting functions stay byte-identical; the plan self-checks inside `structured_plan_inner`
    // still gate admission of the destraddled graph.
    {
        if let Some(destraddled) = restructure_straddle_loop_merges(blocks) {
            if let Some(plan) =
                structured_plan_inner4(&destraddled, force_converge, false, false, allow_bare_exit)
            {
                return Some(plan);
            }
            if let Some(plan) =
                structured_plan_inner4(&destraddled, true, false, false, allow_bare_exit)
            {
                return Some(plan);
            }
            if let Some(plan) =
                structured_plan_inner4(&destraddled, true, true, false, allow_bare_exit)
            {
                return Some(plan);
            }
        }
    }
    // Attempt 6b (Keystone 2 M3): the straddle whose loop-merge ⇄ enclosing-selection-merge collision
    // only MATERIALIZES once the converge/break-aware transforms split the blocks (`04/7da629e9`). The
    // 6th attempt's `restructure_straddle_loop_merges` derives its maps on the ORIGINAL blocks (converge
    // off, break-aware off) and returns `None` for it; running detection under converge+break-aware makes
    // the derived straddle visible, then the destraddled graph re-runs the inner ladder. Reached only
    // after every prior attempt rejects → admitting functions byte-identical.
    {
        if let Some(destraddled) = restructure_straddle_loop_merges_with(blocks, true, true) {
            if let Some(plan) =
                structured_plan_inner4(&destraddled, true, false, false, allow_bare_exit)
            {
                return Some(plan);
            }
            if let Some(plan) =
                structured_plan_inner4(&destraddled, true, true, false, allow_bare_exit)
            {
                return Some(plan);
            }
            // The straddle split can reveal a residual cross-arm-shared selection underneath (the loop
            // now has its own merge, but a post-loop selection still shares an arm). Chain the
            // merge-preserving region clone on the destraddled graph and re-run the ladder.
            let region2 = privatize_region_cross_arm_for_ladder(&destraddled);
            if region2.len() != destraddled.len() {
                if let Some(plan) =
                    structured_plan_inner4(&region2, true, false, false, allow_bare_exit)
                {
                    return Some(plan);
                }
                if let Some(plan) =
                    structured_plan_inner4(&region2, true, true, false, allow_bare_exit)
                {
                    return Some(plan);
                }
            }
        }
    }
    // Seventh attempt (Keystone 2): the ladder
    // rung the 66-case residual census found missing — the region-clone graph (attempt 3) is never
    // combined with converge/break-aware, yet the M2/O3 residual (a converged multi-exit dispatch arm
    // that is ALSO the enclosing guard's direct arm) needs BOTH the region privatization AND the
    // converge transforms. Reached only after every prior attempt rejects → admitting functions stay
    // byte-identical; the plan self-checks still gate admission of the cloned graph.
    if region.len() != blocks.len() {
        if let Some(plan) = structured_plan_inner4(&region, true, false, false, allow_bare_exit) {
            return Some(plan);
        }
        if let Some(plan) = structured_plan_inner4(&region, true, true, false, allow_bare_exit) {
            return Some(plan);
        }
    }
    // Eighth attempt (Keystone 2 M2):
    // the multi-exit shared-exit region clone. When `synth_multi_exit_merge` funnels a 2-exit loop through
    // a dispatch `M`, an exit ALSO reached from outside the loop is not `M`-dominated, so `M`'s dispatch
    // selection cannot own it (the M2 `selection:cond-phi-shared/loop-role/merge-inloop` residual —
    // `02/590c6cf2`). Enabling `multi_exit_clone` clones that exit's dominated forward region into an
    // `M`-dominated copy so both dispatch arms reconverge at a private merge. Reached ONLY after every
    // prior attempt rejects, so a function admitting earlier stays byte-identical — the clone must NOT
    // run on the base attempts (it corrupts an already-valid dispatch into a reject→repair). The
    // residual dispatch is only exposed once the converge/break-aware transforms split the in-loop
    // guard AND (for the `590c6cf2` shape) the region-cross-arm pre-pass privatizes the enclosing
    // selection, so the clone is retried across the same pre-pass combos the ladder uses. The plan
    // self-checks inside `structured_plan_inner4` still gate admission; the switch guard keeps the
    // dead-end #6 multi-level-break switches on the relooper retry path.
    if !switch_gate_excludes(blocks) {
        for &(bl, cv, br) in &[
            (blocks, force_converge, false),
            (blocks, true, false),
            (blocks, true, true),
        ] {
            if let Some(plan) = structured_plan_inner4(bl, cv, br, true, allow_bare_exit) {
                return Some(plan);
            }
        }
        if region.len() != blocks.len() {
            for &(cv, br) in &[(force_converge, false), (true, false), (true, true)] {
                if let Some(plan) = structured_plan_inner4(&region, cv, br, true, allow_bare_exit) {
                    return Some(plan);
                }
            }
        }
    }
    // Ninth attempt (Keystone 2): the cross-arm-EDGE clone.
    // Self-check 3 rejects a DEFINITIVE cross-arm edge — a block deep in one selection arm
    // branching into a sibling arm of an ancestor selection (the 32-row ADMIT structured-exit family
    // self-check 2 misses). `privatize_cross_arm_edge` clones the sibling-arm block's dominated region
    // for the near-arm entry so the escape becomes a private, header-dominated reconvergence, then the
    // destraddled graph re-runs the inner ladder (base -> converge -> converge+break-aware). Reached
    // ONLY after every prior attempt rejects, so a currently-admitting function stays byte-identical; the
    // plan self-checks (including the cross-arm-edge self-check itself) still gate admission of the
    // cloned graph, so an unfixable residue rejects honestly and falls to the relooper retry.
    if blocks.len() <= CROSS_ARM_EDGE_MAX_BLOCKS {
        let cloned = super::clone_crossarm::privatize_cross_arm_edge(blocks);
        if cloned.len() != blocks.len() && cloned.len() <= CROSS_ARM_EDGE_MAX_BLOCKS {
            for &(cv, br) in &[(force_converge, false), (true, false), (true, true)] {
                if let Some(plan) = structured_plan_inner4(&cloned, cv, br, false, allow_bare_exit)
                {
                    return Some(plan);
                }
            }
        }
    }
    // Tenth attempt (Keystone 2): the synthesis-aware
    // cross-arm-SHARED clone. `privatize_synthesized_cross_arm_shared` DERIVES the synthesized merge map
    // to LOCATE the raw `(header, arm)` of a `cross-arm-shared` violation whose merge is a synthesized
    // `%…lmerge.sel*` block, then clones `arm`'s region on the RAW blocks so the re-run synthesizes once
    // cleanly. Pairs with the multi-boundary compound (nested) handling. Reject-triggered so
    // admitting functions stay byte-identical; the plan self-checks gate the cloned result.
    if blocks.len() <= CROSS_ARM_EDGE_MAX_BLOCKS {
        for &(dcv, dbr) in &[(true, true), (force_converge, false), (true, false)] {
            let cloned = privatize_synthesized_cross_arm_shared(blocks, dcv, dbr);
            if cloned.len() != blocks.len() && cloned.len() <= CROSS_ARM_EDGE_MAX_BLOCKS {
                for &(cv, br) in &[(force_converge, false), (true, false), (true, true)] {
                    if let Some(plan) =
                        structured_plan_inner4(&cloned, cv, br, false, allow_bare_exit)
                    {
                        return Some(plan);
                    }
                }
            }
        }
    }
    // Terminal-return planning builds a fixed point and then evaluates several loop-policy variants.
    // Keep it as the true last resort: straddle and cross-arm repairs operate on the compact source CFG
    // and directly address their corresponding self-check classes, whereas terminal ownership can
    // expand deeply nested early-return control flow substantially without removing either defect.
    // Already-admitted functions returned above, so this ordering changes only rejected-CFG work.
    if let Some(plan) = structured_plan_terminal_attempts(blocks, allow_bare_exit) {
        return Some(plan);
    }
    None
}

pub(in crate::native) fn privatize_region_cross_arm_for_ladder(
    blocks: &[BodyBlock],
) -> Vec<BodyBlock> {
    if blocks.len() > REGION_CROSS_ARM_LADDER_MAX_BLOCKS {
        blocks.to_vec()
    } else {
        let cloned = super::clone_crossarm::privatize_region_cross_arm(blocks);
        if cloned.len() > REGION_CROSS_ARM_LADDER_MAX_BLOCKS {
            blocks.to_vec()
        } else {
            cloned
        }
    }
}

pub(in crate::native) fn privatize_shared_continuations_for_ladder(
    blocks: &[BodyBlock],
) -> Vec<BodyBlock> {
    if blocks.len() > SHARED_CONTINUATION_LADDER_MAX_BLOCKS {
        return blocks.to_vec();
    }
    let switch_private = super::clone_crossarm::privatize_switch_case_continuations(blocks);
    if switch_private.len() > SHARED_CONTINUATION_LADDER_MAX_BLOCKS {
        return blocks.to_vec();
    }
    let deep_shared = super::clone_crossarm::privatize_deep_shared_continuations(&switch_private);
    if deep_shared.len() > SHARED_CONTINUATION_LADDER_MAX_BLOCKS {
        blocks.to_vec()
    } else {
        deep_shared
    }
}

pub(in crate::native) fn selection_synth_growth_exceeds_ladder_cap(
    source_blocks: usize,
    synthesized_blocks: usize,
) -> bool {
    let allowed_growth = SELECTION_SYNTH_GROWTH_MAX_BLOCKS.max(source_blocks);
    synthesized_blocks.saturating_sub(source_blocks) > allowed_growth
}

pub(in crate::native) fn is_switch_block(b: &BodyBlock) -> bool {
    // Read the structured terminator from the carrier (the sole substrate); a block whose lines did not
    // lower (`typed: None`) has no terminator and is not a switch.
    b.typed.as_ref().is_some_and(|carrier| {
        matches!(
            carrier.terminator,
            crate::native::tir::TirTerminator::Switch { .. }
        )
    })
}

/// Does any switch-terminating block form a MULTI-LEVEL BREAK — a switch inside a natural loop body
/// with an arm (case/default target) that EXITS that loop? That is the dead-end #6 shape (the
/// OpSwitch's arm targets the enclosing loop's merge, breaking the loop while skipping the switch's own
/// selection merge — `Switch header does not structurally dominate its case construct`), which the
/// source-CFG dominance self-check cannot reject, so the 5th/6th/7th attempts would over-admit it into
/// invalid SPIR-V. A switch NOT enclosed by any loop, or one whose every arm stays inside its enclosing
/// loop, reconverges normally and is safe to admit. This is the precise M1b narrowing (guard-off would
/// admit 35 more banked cases but break these 3: `02/387ebaa9`/`04/4b57a380`/`12/01d1972c`). See
/// [[metal2vulkan-native-emitter]] M1b.
pub(in crate::native) fn blocks_contain_multilevel_break_switch(blocks: &[BodyBlock]) -> bool {
    let switch_succs: HashMap<&str, Vec<String>> = blocks
        .iter()
        .filter(|b| is_switch_block(b))
        .map(|b| (b.name.as_str(), block_successors(b)))
        .collect();
    if switch_succs.is_empty() {
        return false;
    }
    let forest = analyze(blocks);
    for l in &forest.loops {
        let body: HashSet<&str> = l.body.iter().map(String::as_str).collect();
        for (name, succs) in &switch_succs {
            // The header's own multi-successor exit is a legal loop exit test, not a multi-level break.
            if *name == l.header.as_str() || !body.contains(name) {
                continue;
            }
            if succs.iter().any(|s| !body.contains(s.as_str())) {
                return true;
            }
        }
    }
    false
}

/// The switch guard for the 5th/6th/7th `structured_plan` attempts (M1b): exclude only the genuine
/// multi-level-break shape ([`blocks_contain_multilevel_break_switch`]) so a loop-free switch — or an
/// in-loop switch whose arms all stay inside the loop — reaches the attempts. (The prior blanket guard
/// excluded any switch-bearing function, the conservative front-stop for dead-end #6.)
pub(in crate::native) fn switch_gate_excludes(blocks: &[BodyBlock]) -> bool {
    blocks_contain_multilevel_break_switch(blocks)
}
