// AUTOMATICALLY GENERATED from the Khronos SPIR-V core grammar JSON
// (SPIRV-Headers tag vulkan-sdk-1.4.341.0: include/spirv/unified1/spirv.core.grammar.json)
// via https://github.com/gfx-rs/rspirv autogen, then adapted for this crate.
// DO NOT HAND-EDIT — regenerate with scripts/regen-spirv-grammar/regen-spirv-grammar.sh

impl fmt::Display for Operand {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match *self {
            Operand::ImageOperands(ref v) => write!(f, "{:?}", v),
            Operand::FPFastMathMode(ref v) => write!(f, "{:?}", v),
            Operand::SelectionControl(ref v) => write!(f, "{:?}", v),
            Operand::LoopControl(ref v) => write!(f, "{:?}", v),
            Operand::FunctionControl(ref v) => write!(f, "{:?}", v),
            Operand::MemorySemantics(ref v) => write!(f, "{:?}", v),
            Operand::MemoryAccess(ref v) => write!(f, "{:?}", v),
            Operand::KernelProfilingInfo(ref v) => write!(f, "{:?}", v),
            Operand::RayFlags(ref v) => write!(f, "{:?}", v),
            Operand::FragmentShadingRate(ref v) => write!(f, "{:?}", v),
            Operand::RawAccessChainOperands(ref v) => write!(f, "{:?}", v),
            Operand::SourceLanguage(ref v) => write!(f, "{:?}", v),
            Operand::ExecutionModel(ref v) => write!(f, "{:?}", v),
            Operand::AddressingModel(ref v) => write!(f, "{:?}", v),
            Operand::MemoryModel(ref v) => write!(f, "{:?}", v),
            Operand::ExecutionMode(ref v) => write!(f, "{:?}", v),
            Operand::StorageClass(ref v) => write!(f, "{:?}", v),
            Operand::Dim(ref v) => write!(f, "{}", &format!("{:?}", v)[3..]),
            Operand::SamplerAddressingMode(ref v) => write!(f, "{:?}", v),
            Operand::SamplerFilterMode(ref v) => write!(f, "{:?}", v),
            Operand::ImageFormat(ref v) => write!(f, "{:?}", v),
            Operand::ImageChannelOrder(ref v) => write!(f, "{:?}", v),
            Operand::ImageChannelDataType(ref v) => write!(f, "{:?}", v),
            Operand::FPRoundingMode(ref v) => write!(f, "{:?}", v),
            Operand::FPDenormMode(ref v) => write!(f, "{:?}", v),
            Operand::QuantizationModes(ref v) => write!(f, "{:?}", v),
            Operand::FPOperationMode(ref v) => write!(f, "{:?}", v),
            Operand::OverflowModes(ref v) => write!(f, "{:?}", v),
            Operand::LinkageType(ref v) => write!(f, "{:?}", v),
            Operand::AccessQualifier(ref v) => write!(f, "{:?}", v),
            Operand::HostAccessQualifier(ref v) => write!(f, "{:?}", v),
            Operand::FunctionParameterAttribute(ref v) => write!(f, "{:?}", v),
            Operand::Decoration(ref v) => write!(f, "{:?}", v),
            Operand::BuiltIn(ref v) => write!(f, "{:?}", v),
            Operand::Scope(ref v) => write!(f, "{:?}", v),
            Operand::GroupOperation(ref v) => write!(f, "{:?}", v),
            Operand::KernelEnqueueFlags(ref v) => write!(f, "{:?}", v),
            Operand::Capability(ref v) => write!(f, "{:?}", v),
            Operand::RayQueryIntersection(ref v) => write!(f, "{:?}", v),
            Operand::RayQueryCommittedIntersectionType(ref v) => write!(f, "{:?}", v),
            Operand::RayQueryCandidateIntersectionType(ref v) => write!(f, "{:?}", v),
            Operand::PackedVectorFormat(ref v) => write!(f, "{:?}", v),
            Operand::CooperativeMatrixOperands(ref v) => write!(f, "{:?}", v),
            Operand::CooperativeMatrixLayout(ref v) => write!(f, "{:?}", v),
            Operand::CooperativeMatrixUse(ref v) => write!(f, "{:?}", v),
            Operand::CooperativeMatrixReduce(ref v) => write!(f, "{:?}", v),
            Operand::TensorClampMode(ref v) => write!(f, "{:?}", v),
            Operand::TensorAddressingOperands(ref v) => write!(f, "{:?}", v),
            Operand::InitializationModeQualifier(ref v) => write!(f, "{:?}", v),
            Operand::LoadCacheControl(ref v) => write!(f, "{:?}", v),
            Operand::StoreCacheControl(ref v) => write!(f, "{:?}", v),
            Operand::NamedMaximumNumberOfRegisters(ref v) => write!(f, "{:?}", v),
            Operand::MatrixMultiplyAccumulateOperands(ref v) => write!(f, "{:?}", v),
            Operand::FPEncoding(ref v) => write!(f, "{:?}", v),
            Operand::CooperativeVectorMatrixLayout(ref v) => write!(f, "{:?}", v),
            Operand::ComponentType(ref v) => write!(f, "{:?}", v),
            Operand::IdMemorySemantics(ref v) => write!(f, "%{}", v),
            Operand::IdScope(ref v) => write!(f, "%{}", v),
            Operand::IdRef(ref v) => write!(f, "%{}", v),
            Operand::LiteralString(ref v) => write!(f, "{:?}", v),
            Operand::LiteralExtInstInteger(ref v) => write!(f, "{:?}", v),
            Operand::LiteralSpecConstantOpInteger(ref v) => write!(f, "{:?}", v),
            Operand::TensorOperands(ref v) => write!(f, "{:?}", v),
            Operand::LiteralBit32(ref v) => write!(f, "{:?}", v),
            Operand::LiteralBit64(ref v) => write!(f, "{:?}", v),
        }
    }
}